[tool.black]
target-version = ["py313"]

[tool.isort]
profile = "black"

[tool.ruff.lint]
select = ["E", "F", "W"]
ignore = ["E501", "E741", "F401"]

[tool.bandit]
exclude_dirs = ["tests"]

[tool.djlint]
ignore = "H006,H021"


[tool.mypy]
mypy_path = "."
python_version = "3.13"
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
warn_return_any = true
explicit_package_bases = true
namespace_packages = true
ignore_missing_imports = true
plugins = "mypy_django_plugin.main"

[mypy.plugins.django-stubs]
django_settings_module = "core.settings"
